<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="DWORD_TO_SIZE" Id="{0c094056-a599-4c54-8e98-f63319bc1ae2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION DWORD_TO_SIZE : ST_SIZE
VAR_INPUT
	nValue : DWORD;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[DWORD_TO_SIZE.nValue := nValue;
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>