<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="UDINT_TO_SIZE" Id="{b65a5d58-2b30-41bf-b54e-292bc4b7f4b4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION UDINT_TO_SIZE : ST_SIZE
VAR_INPUT
	nValue : UDINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[UDINT_TO_SIZE.nValue := nValue;
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>