<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="UINT_TO_SIZE" Id="{1e36d644-d847-4e21-8285-fe5478178171}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION UINT_TO_SIZE : ST_SIZE
VAR_INPUT
	nValue : UINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[UINT_TO_SIZE.nValue := nValue;
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>