<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="USINT_TO_SIZE" Id="{9b40cfa9-38a6-4876-bff1-58d5fb6caed7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION USINT_TO_SIZE : ST_SIZE
VAR_INPUT
	nValue : USINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[USINT_TO_SIZE.nValue := nValue;
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>