<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="WORD_TO_SIZE" Id="{9dff1bdf-2064-485c-9750-00be1ec72651}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION WORD_TO_SIZE : ST_SIZE
VAR_INPUT
	nValue : WORD;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[WORD_TO_SIZE.nValue := nValue;
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>